spring.datasource.url=jdbc:mysql://localhost:3306/turnosmart
spring.datasource.username=root
spring.datasource.password=data2026-

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.turnosmart=DEBUG
logging.file.name=logs/turnosmart.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n